apiVersion: v1
kind: ResourceQuota
metadata:
  name: core-object-counts
spec:
  hard:
    configmaps: "10"
    replicationcontrollers: "10"
    secrets: "20"
    services: "10"
    resourcequotas: "10"
    persistentvolumeclaims: "10"
    openshift.io/imagestreams: "10"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    pods: "12"
    limits.memory: "14Gi"
  scopes:
  - NotTerminating
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: storage-consumption
spec:
  hard:
    persistentvolumeclaims: "10"
    requests.storage: "50Gi"